In [1]:
import numpy as np
import pandas as pd

decision_matrix = np.array([[250, 16, 12, 5],
                            [200, 16, 12, 3],
                            [300, 16, 12, 4],
                            [275, 32, 8,  4],
                            [225, 16, 16, 2]
                            ])

In [47]:
weights = np.array([0.25, 0.25, 0.25, 0.25])


In [48]:
normalized_matrix = decision_matrix / np.sqrt(decision_matrix **2).sum(axis=0)
normalized_matrix

array([[0.2       , 0.16666667, 0.2       , 0.27777778],
       [0.16      , 0.16666667, 0.2       , 0.16666667],
       [0.24      , 0.16666667, 0.2       , 0.22222222],
       [0.22      , 0.33333333, 0.13333333, 0.22222222],
       [0.18      , 0.16666667, 0.26666667, 0.11111111]])

In [49]:
weighted_normalised_matrix = normalized_matrix * weights
weighted_normalised_matrix

array([[0.05      , 0.04166667, 0.05      , 0.06944444],
       [0.04      , 0.04166667, 0.05      , 0.04166667],
       [0.06      , 0.04166667, 0.05      , 0.05555556],
       [0.055     , 0.08333333, 0.03333333, 0.05555556],
       [0.045     , 0.04166667, 0.06666667, 0.02777778]])

In [50]:
ideal_best = np.array([weighted_normalised_matrix[:, i].max() if weights[i] > 0 else weighted_normalised_matrix[:, i].min() for i in range(len(weights))])
ideal_best

array([0.06      , 0.08333333, 0.06666667, 0.06944444])

In [51]:
ideal_worst =  np.array([weighted_normalised_matrix[:, i].min() if weights[i] > 0 else weighted_normalised_matrix[:, i].max() for i in range(len(weights))])
ideal_worst

array([0.04      , 0.04166667, 0.03333333, 0.02777778])

In [52]:
euclidean_distance_ideal_best = np.sqrt(((weighted_normalised_matrix - ideal_best) ** 2).sum(axis=1))
euclidean_distance_ideal_best

array([0.04597705, 0.05644018, 0.04697648, 0.03645562, 0.06080479])

In [53]:
euclidean_distance_ideal_worst= np.sqrt(((weighted_normalised_matrix - ideal_worst) ** 2).sum(axis=1))
euclidean_distance_ideal_worst

array([0.04597705, 0.02169514, 0.03807076, 0.05227539, 0.03370625])

In [54]:
preferences = euclidean_distance_ideal_worst / (euclidean_distance_ideal_best + euclidean_distance_ideal_worst)
preferences

array([0.5       , 0.2776611 , 0.44764248, 0.58914451, 0.35663822])

In [55]:
best_alternative = np.argsort(preferences)
best_alternative

array([1, 4, 2, 0, 3])

In [56]:
print("Preferences:", preferences)
print(preferences)
print("\nBest Alternatives:", best_alternative)
print("Rank:", best_alternative + 1)

Preferences: [0.5        0.2776611  0.44764248 0.58914451 0.35663822]
[0.5        0.2776611  0.44764248 0.58914451 0.35663822]

Best Alternatives: [1 4 2 0 3]
Rank: [2 5 3 1 4]
